export { default as Navbar } from './navbar/navbar' 
export { default as TopNav } from './top-nav/top-nav' 
export { default as BottomNav } from './bottom-nav/bottom-nav' 
export { default as Footer } from './footer/footer' 
export { default as ButtonUI } from './ui/Button-UI' 
export { default as DropdownUI } from './ui/Dropdown-UI' 
export { default as InfoProductPrice } from './ui/InfoProductPrice'
export { default as InfoProductUI } from './ui/Info-Product-UI'
export { default as ImageUI } from './ui/Image-UI'
export { default as SectionUI } from './ui/Section-UI' 
export { default as SectionTitle } from './section-title/section-title' 
export { default as Header } from './header/header' 
export { default as SwiperBanner } from './swiper-banner/swiper-banner' 
export { default as FigureAnimation } from './figure-animation/figure-animation' 
export { default as CategoryBtn} from './category-btn/category-btn'
export { default as ProductCard} from './product-card/product-card'
export { default as ProductSlider} from './products-slider/products-slider'
export { default as PartnorsSlider} from './partnors-slider/partnors-slider'
export { default as Breadcrumb} from './breadcrumb/breadcrumb'
export { default as OrderCard} from './order-card/order-card'
export { default as Counter } from  './counter/counter'
export { default as SearchPanel } from  './search-panel/search-panel'
export { default as Advantages } from  './advantages/advantages'
